# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jacob/Desktop/verilog_compiler

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jacob/Desktop/verilog_compiler

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jacob/Desktop/verilog_compiler/CMakeFiles /home/jacob/Desktop/verilog_compiler/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jacob/Desktop/verilog_compiler/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SRCLIB

# Build rule for target.
SRCLIB: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SRCLIB
.PHONY : SRCLIB

# fast build rule for target.
SRCLIB/fast:
	$(MAKE) -f CMakeFiles/SRCLIB.dir/build.make CMakeFiles/SRCLIB.dir/build
.PHONY : SRCLIB/fast

#=============================================================================
# Target rules for targets named check

# Build rule for target.
check: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check
.PHONY : check

# fast build rule for target.
check/fast:
	$(MAKE) -f CMakeFiles/check.dir/build.make CMakeFiles/check.dir/build
.PHONY : check/fast

#=============================================================================
# Target rules for targets named LexerTest

# Build rule for target.
LexerTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 LexerTest
.PHONY : LexerTest

# fast build rule for target.
LexerTest/fast:
	$(MAKE) -f bin/test/CMakeFiles/LexerTest.dir/build.make bin/test/CMakeFiles/LexerTest.dir/build
.PHONY : LexerTest/fast

#=============================================================================
# Target rules for targets named DestinationTest

# Build rule for target.
DestinationTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 DestinationTest
.PHONY : DestinationTest

# fast build rule for target.
DestinationTest/fast:
	$(MAKE) -f bin/test/CMakeFiles/DestinationTest.dir/build.make bin/test/CMakeFiles/DestinationTest.dir/build
.PHONY : DestinationTest/fast

#=============================================================================
# Target rules for targets named TokenTest

# Build rule for target.
TokenTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TokenTest
.PHONY : TokenTest

# fast build rule for target.
TokenTest/fast:
	$(MAKE) -f bin/test/CMakeFiles/TokenTest.dir/build.make bin/test/CMakeFiles/TokenTest.dir/build
.PHONY : TokenTest/fast

#=============================================================================
# Target rules for targets named ErrorTest

# Build rule for target.
ErrorTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ErrorTest
.PHONY : ErrorTest

# fast build rule for target.
ErrorTest/fast:
	$(MAKE) -f bin/test/CMakeFiles/ErrorTest.dir/build.make bin/test/CMakeFiles/ErrorTest.dir/build
.PHONY : ErrorTest/fast

#=============================================================================
# Target rules for targets named ErrorLogTest

# Build rule for target.
ErrorLogTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ErrorLogTest
.PHONY : ErrorLogTest

# fast build rule for target.
ErrorLogTest/fast:
	$(MAKE) -f bin/test/CMakeFiles/ErrorLogTest.dir/build.make bin/test/CMakeFiles/ErrorLogTest.dir/build
.PHONY : ErrorLogTest/fast

#=============================================================================
# Target rules for targets named PositionTest

# Build rule for target.
PositionTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PositionTest
.PHONY : PositionTest

# fast build rule for target.
PositionTest/fast:
	$(MAKE) -f bin/test/CMakeFiles/PositionTest.dir/build.make bin/test/CMakeFiles/PositionTest.dir/build
.PHONY : PositionTest/fast

#=============================================================================
# Target rules for targets named SourceTest

# Build rule for target.
SourceTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SourceTest
.PHONY : SourceTest

# fast build rule for target.
SourceTest/fast:
	$(MAKE) -f bin/test/CMakeFiles/SourceTest.dir/build.make bin/test/CMakeFiles/SourceTest.dir/build
.PHONY : SourceTest/fast

src/Token.o: src/Token.cpp.o

.PHONY : src/Token.o

# target to build an object file
src/Token.cpp.o:
	$(MAKE) -f CMakeFiles/SRCLIB.dir/build.make CMakeFiles/SRCLIB.dir/src/Token.cpp.o
.PHONY : src/Token.cpp.o

src/Token.i: src/Token.cpp.i

.PHONY : src/Token.i

# target to preprocess a source file
src/Token.cpp.i:
	$(MAKE) -f CMakeFiles/SRCLIB.dir/build.make CMakeFiles/SRCLIB.dir/src/Token.cpp.i
.PHONY : src/Token.cpp.i

src/Token.s: src/Token.cpp.s

.PHONY : src/Token.s

# target to generate assembly for a file
src/Token.cpp.s:
	$(MAKE) -f CMakeFiles/SRCLIB.dir/build.make CMakeFiles/SRCLIB.dir/src/Token.cpp.s
.PHONY : src/Token.cpp.s

src/common/Colors.o: src/common/Colors.cpp.o

.PHONY : src/common/Colors.o

# target to build an object file
src/common/Colors.cpp.o:
	$(MAKE) -f CMakeFiles/SRCLIB.dir/build.make CMakeFiles/SRCLIB.dir/src/common/Colors.cpp.o
.PHONY : src/common/Colors.cpp.o

src/common/Colors.i: src/common/Colors.cpp.i

.PHONY : src/common/Colors.i

# target to preprocess a source file
src/common/Colors.cpp.i:
	$(MAKE) -f CMakeFiles/SRCLIB.dir/build.make CMakeFiles/SRCLIB.dir/src/common/Colors.cpp.i
.PHONY : src/common/Colors.cpp.i

src/common/Colors.s: src/common/Colors.cpp.s

.PHONY : src/common/Colors.s

# target to generate assembly for a file
src/common/Colors.cpp.s:
	$(MAKE) -f CMakeFiles/SRCLIB.dir/build.make CMakeFiles/SRCLIB.dir/src/common/Colors.cpp.s
.PHONY : src/common/Colors.cpp.s

src/common/Destination.o: src/common/Destination.cpp.o

.PHONY : src/common/Destination.o

# target to build an object file
src/common/Destination.cpp.o:
	$(MAKE) -f CMakeFiles/SRCLIB.dir/build.make CMakeFiles/SRCLIB.dir/src/common/Destination.cpp.o
.PHONY : src/common/Destination.cpp.o

src/common/Destination.i: src/common/Destination.cpp.i

.PHONY : src/common/Destination.i

# target to preprocess a source file
src/common/Destination.cpp.i:
	$(MAKE) -f CMakeFiles/SRCLIB.dir/build.make CMakeFiles/SRCLIB.dir/src/common/Destination.cpp.i
.PHONY : src/common/Destination.cpp.i

src/common/Destination.s: src/common/Destination.cpp.s

.PHONY : src/common/Destination.s

# target to generate assembly for a file
src/common/Destination.cpp.s:
	$(MAKE) -f CMakeFiles/SRCLIB.dir/build.make CMakeFiles/SRCLIB.dir/src/common/Destination.cpp.s
.PHONY : src/common/Destination.cpp.s

src/common/Error.o: src/common/Error.cpp.o

.PHONY : src/common/Error.o

# target to build an object file
src/common/Error.cpp.o:
	$(MAKE) -f CMakeFiles/SRCLIB.dir/build.make CMakeFiles/SRCLIB.dir/src/common/Error.cpp.o
.PHONY : src/common/Error.cpp.o

src/common/Error.i: src/common/Error.cpp.i

.PHONY : src/common/Error.i

# target to preprocess a source file
src/common/Error.cpp.i:
	$(MAKE) -f CMakeFiles/SRCLIB.dir/build.make CMakeFiles/SRCLIB.dir/src/common/Error.cpp.i
.PHONY : src/common/Error.cpp.i

src/common/Error.s: src/common/Error.cpp.s

.PHONY : src/common/Error.s

# target to generate assembly for a file
src/common/Error.cpp.s:
	$(MAKE) -f CMakeFiles/SRCLIB.dir/build.make CMakeFiles/SRCLIB.dir/src/common/Error.cpp.s
.PHONY : src/common/Error.cpp.s

src/common/ErrorLog.o: src/common/ErrorLog.cpp.o

.PHONY : src/common/ErrorLog.o

# target to build an object file
src/common/ErrorLog.cpp.o:
	$(MAKE) -f CMakeFiles/SRCLIB.dir/build.make CMakeFiles/SRCLIB.dir/src/common/ErrorLog.cpp.o
.PHONY : src/common/ErrorLog.cpp.o

src/common/ErrorLog.i: src/common/ErrorLog.cpp.i

.PHONY : src/common/ErrorLog.i

# target to preprocess a source file
src/common/ErrorLog.cpp.i:
	$(MAKE) -f CMakeFiles/SRCLIB.dir/build.make CMakeFiles/SRCLIB.dir/src/common/ErrorLog.cpp.i
.PHONY : src/common/ErrorLog.cpp.i

src/common/ErrorLog.s: src/common/ErrorLog.cpp.s

.PHONY : src/common/ErrorLog.s

# target to generate assembly for a file
src/common/ErrorLog.cpp.s:
	$(MAKE) -f CMakeFiles/SRCLIB.dir/build.make CMakeFiles/SRCLIB.dir/src/common/ErrorLog.cpp.s
.PHONY : src/common/ErrorLog.cpp.s

src/common/Position.o: src/common/Position.cpp.o

.PHONY : src/common/Position.o

# target to build an object file
src/common/Position.cpp.o:
	$(MAKE) -f CMakeFiles/SRCLIB.dir/build.make CMakeFiles/SRCLIB.dir/src/common/Position.cpp.o
.PHONY : src/common/Position.cpp.o

src/common/Position.i: src/common/Position.cpp.i

.PHONY : src/common/Position.i

# target to preprocess a source file
src/common/Position.cpp.i:
	$(MAKE) -f CMakeFiles/SRCLIB.dir/build.make CMakeFiles/SRCLIB.dir/src/common/Position.cpp.i
.PHONY : src/common/Position.cpp.i

src/common/Position.s: src/common/Position.cpp.s

.PHONY : src/common/Position.s

# target to generate assembly for a file
src/common/Position.cpp.s:
	$(MAKE) -f CMakeFiles/SRCLIB.dir/build.make CMakeFiles/SRCLIB.dir/src/common/Position.cpp.s
.PHONY : src/common/Position.cpp.s

src/common/Source.o: src/common/Source.cpp.o

.PHONY : src/common/Source.o

# target to build an object file
src/common/Source.cpp.o:
	$(MAKE) -f CMakeFiles/SRCLIB.dir/build.make CMakeFiles/SRCLIB.dir/src/common/Source.cpp.o
.PHONY : src/common/Source.cpp.o

src/common/Source.i: src/common/Source.cpp.i

.PHONY : src/common/Source.i

# target to preprocess a source file
src/common/Source.cpp.i:
	$(MAKE) -f CMakeFiles/SRCLIB.dir/build.make CMakeFiles/SRCLIB.dir/src/common/Source.cpp.i
.PHONY : src/common/Source.cpp.i

src/common/Source.s: src/common/Source.cpp.s

.PHONY : src/common/Source.s

# target to generate assembly for a file
src/common/Source.cpp.s:
	$(MAKE) -f CMakeFiles/SRCLIB.dir/build.make CMakeFiles/SRCLIB.dir/src/common/Source.cpp.s
.PHONY : src/common/Source.cpp.s

src/main/Lexer.o: src/main/Lexer.cpp.o

.PHONY : src/main/Lexer.o

# target to build an object file
src/main/Lexer.cpp.o:
	$(MAKE) -f CMakeFiles/SRCLIB.dir/build.make CMakeFiles/SRCLIB.dir/src/main/Lexer.cpp.o
.PHONY : src/main/Lexer.cpp.o

src/main/Lexer.i: src/main/Lexer.cpp.i

.PHONY : src/main/Lexer.i

# target to preprocess a source file
src/main/Lexer.cpp.i:
	$(MAKE) -f CMakeFiles/SRCLIB.dir/build.make CMakeFiles/SRCLIB.dir/src/main/Lexer.cpp.i
.PHONY : src/main/Lexer.cpp.i

src/main/Lexer.s: src/main/Lexer.cpp.s

.PHONY : src/main/Lexer.s

# target to generate assembly for a file
src/main/Lexer.cpp.s:
	$(MAKE) -f CMakeFiles/SRCLIB.dir/build.make CMakeFiles/SRCLIB.dir/src/main/Lexer.cpp.s
.PHONY : src/main/Lexer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... test"
	@echo "... SRCLIB"
	@echo "... check"
	@echo "... LexerTest"
	@echo "... DestinationTest"
	@echo "... TokenTest"
	@echo "... ErrorTest"
	@echo "... ErrorLogTest"
	@echo "... PositionTest"
	@echo "... SourceTest"
	@echo "... src/Token.o"
	@echo "... src/Token.i"
	@echo "... src/Token.s"
	@echo "... src/common/Colors.o"
	@echo "... src/common/Colors.i"
	@echo "... src/common/Colors.s"
	@echo "... src/common/Destination.o"
	@echo "... src/common/Destination.i"
	@echo "... src/common/Destination.s"
	@echo "... src/common/Error.o"
	@echo "... src/common/Error.i"
	@echo "... src/common/Error.s"
	@echo "... src/common/ErrorLog.o"
	@echo "... src/common/ErrorLog.i"
	@echo "... src/common/ErrorLog.s"
	@echo "... src/common/Position.o"
	@echo "... src/common/Position.i"
	@echo "... src/common/Position.s"
	@echo "... src/common/Source.o"
	@echo "... src/common/Source.i"
	@echo "... src/common/Source.s"
	@echo "... src/main/Lexer.o"
	@echo "... src/main/Lexer.i"
	@echo "... src/main/Lexer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

